### ISSUE TITLE
Consider adding attoparsec to common dependencies for wordy exercise

### ISSUE THREAD

**Issue by mike-barber** [exercism/haskell#1044]
I've been trying to submit a (locally-working) solution to the [wordy](https://github.com/exercism/haskell/tree/main/exercises/practice/wordy) exercise, but it's failing to download `attoparsec` due to an `HttpExceptionRequest`. I am submitting both `package.yaml` and the source.

I originally used `megaparsec` but ran into the same issue. The exercise itself suggests that "This is a perfect opportunity to learn some Attoparsec or Parsec!", so I figured `attoparsec` might be a better option given the recommendation.

I may be missing a workaround here, but from surveying recent issues it appears that packages required need to be baked into the test runner here: [pre-compiled/package.yaml](https://github.com/exercism/haskell-test-runner/blob/main/pre-compiled/package.yaml), c.f. [test runner pr 32](https://github.com/exercism/haskell-test-runner/pull/32)

```yaml
library:
  exposed-modules: LeapYear
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - QuickCheck
    - lens
    - parallel
    - vector
    - split
    - random
    - string-conversions
    - text
```

Would the solution to this be to add `attoparsec` to the above, or is there another workaround I should be using?

*EDIT*: I've verified that adding `attoparsec` to the test runner image resolves the problem - tested using `./bin/run-in-docker.sh wordy ...` -- still not sure if this is the preferred solution though.
