### ISSUE TITLE
Build error (connection failure, `Cabal file info not found...`)

### ISSUE THREAD

**Issue by langfield** [exercism/haskell#1123]
This configuration passes the tests on a local `stack` installation, but fails on the website.

```yaml
name: minesweeper
version: 1.1.0.5

dependencies:
  - base

library:
  exposed-modules: Minesweeper
  source-dirs: src
  ghc-options:
    - -Wall
    - -fwrite-ide-info
    - -hiedir=.hie
  dependencies:
    - containers
    - array
    - comfort-array == 0.4.1
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - minesweeper
      - hspec
```

```
Cabal file info not found for comfort-array-0.5.1.1@sha256:77f75e3b1511288db3ea7cac41eb960af6761518a4f48d173120ccf738afa5fa,5572, updating
Selected mirror https://hackage.haskell.org/
Downloading root
HttpExceptionRequest Request {
  host                 = "hackage.haskell.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept-Encoding",""),("User-Agent","Haskell pantry package")]
  path                 = "/root.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "hackage.haskell.org", service name: Just "443"): does not exist (Try again))
```

Any idea what the issue might be?
