### ISSUE TITLE
Moving from Travis to GitHub Actions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/haskell#921]
Hello 🙂 

Over the last few months we've been transferring all our CI from Travis to [GitHub Actions (GHA)](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions). We've found that GHA are easier to work with, more reliable, and much much faster. 

Based on our success with GHA and increasing intermittent failures on Travis, we have now decided to try and remove Travis from Exercism's org altogether and [shift everything to GHA](https://github.com/exercism/exercism/issues/5396). This issue acts as a call to action if your track is still using Travis. 

For most CI checks this should be a transposing from Travis' syntax to [GHA syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions), and hopefully quite straightforward (see [this PR for an example](https://github.com/exercism/csharp/pull/1338/files)).  However, if you do encounter any issues doing this, please ask on Slack where lots of us now have experience with GHA, or post a comment here and I'll tag relevant people. This would also make a good Hacktoberfest issue for anyone interested in making their first contribution 🙂 

If you've already switched this track to GHA, please feel free to close this issue and ignore it.

Thanks!

**Comment by ErikSchierboom** [comment]
Thanks to @SleeplessByte, we now have a really nice document and some starting workflows that you can use to help switch to GitHub Actions: https://github.com/exercism/problem-specifications/tree/master/workflows#workflow-templates

**Comment by petertseng** [comment]
To work on this issue, what you're going to want to do is to move each of the checks in https://github.com/exercism/haskell/blob/master/.travis.yml over, and I recommend doing them piecemeal. For example here is one that will just do `configlet lint`

```yaml
name: Tests
on:
  pull_request:
  push:
    branches:
    - YOURBRANCHNAME

jobs:
  track-config:
    name: Check track configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch
        run: bin/fetch-configlet
      - name: Lint
        run: bin/configlet lint .
```

(Notice where it says YOURBRANCHNAME - use your branch name there so GHA runs on your branch on your repo)

The checks to be moved are as follows. If you have a branch with that particular check moved over, check the box add a link to that branch if you have edit access, otherwise post a comment linking to that branch. When they're all done we'll combine them all.

- [ ] Ensure READMEs updated
- [ ] configlet fmt
- [ ] Ensure stack resolvers synced
- [x] configlet lint  (https://github.com/petertseng/exercism-haskell/blob/gha/.github/workflows/tests.yml)
- [x] check for invalid UUIDs (https://github.com/petertseng/exercism-haskell/blob/gha/.github/workflows/tests.yml)
- [ ] hlint
- [ ] stubs compile
- [ ] Example solutions pass tests
